export default {
       ima:"I'm good in",
      firozsoftwaredevelopmentengineer:"Firoz Software Development Engineer",
       home:"Home",
       about:"About",
       services:"Services",
       skills:"Skills",
       contact:"Contact",
       projects:"Projects",
       resume:"Resume",
       comingSoon:"Coming Soon",
       unlockMyPotentialWithYou:"Bringing Simplicity And Reliability To Complex Software Challenges",
       github:"GitHub",
       githubCode:"GitHub Code",
       projectName:"Project Name",
       aboutProjects:"PROJECTS",
       highlight:"Highlights",
       techStacks:"Tech Stacks",
       html:"HTML",
       css:"CSS",
       reactNative:"React/Native",
       javaScript:"JavaScript",
       dsa:"DSA",
       git:"Git",
       sql:"SQL",
       c:"C",
       cpp:"C++",
       comingSoon:"Coming Soon",
       getInTouch:"get in touch",
       phone:"Phone",
       number:"8743010481",
       email:"Email",
       firozGmailCom:"firozkhandelhi62@gmail.com",
       address:"Address",
       newDelhi:"New Delhi",




}